version: '3'

services:
    composer_installation:
        container_name: composer_installation
        image: composer
        volumes:
            - ./:/app
        command: composer install --ignore-platform-reqs
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./app:/app
    php:
        build:
            context: .
            dockerfile: PHP.Dockerfile
        volumes:
            - ./app:/app
            - ./sql:/docker-entrypoint-initdb.d
            - ./vendor:/vendor
    mysql:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: 'secret123'
            MYSQL_USER: 'developer'
            MYSQL_PASSWORD: 'secret123'
            MYSQL_DATABASE: 'developmentdb'
        volumes:
            - mysqldata:/var/lib/mysql
        ports:
            - 3306:3306
    phpmyadmin:
        image: phpmyadmin:latest
        ports:
            - 8080:80
        environment:
            - PMA_HOST=mysql
        restart: unless-stopped
volumes:
    mysqldata: {}